Bug 558873 - [JUnit 5] Update to JUnit 5.6
Probably related to the error below after update to JUnit from 5.5.1 to
5.6.0?

org.junit.platform.commons.JUnitException: TestEngine with ID
'junit-jupiter' failed to discover tests

Caused by: java.lang.ClassNotFoundException:
org.eclipse.jdt.compiler.tool.tests.AllTests

Change-Id: I5c0a54eac4d92328d69bea56205c0706a39e05ec
Signed-off-by: Andrey Loskutov <loskutov@gmx.de>